### ISSUE TITLE
error roslaunch turtlebot3_autorace_detect turtlebot3_autorace_detect_sign.launch

### ISSUE THREAD

**Issue by touchtsu** [ROBOTIS-GIT/turtlebot3_autorace#14]
I learn turtlebot3 with ROS And have problem about this. http://emanual.robotis.com/docs/en/platform/turtlebot3/autonomous_driving/#tutorials-52-traffic-sign
When I'm run nod with ("

roslaunch turtlebot3_autorace_detect turtlebot3_autorace_detect_sign.launch

")  it's show error like this...
"OpenCV Error: Bad argument (image is empty or has incorrect depth (!=CV_8U)) in detectAndCompute, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/opencv_contrib/xfeatures2d/src/sift.cpp, line 1121
Traceback (most recent call last):
  File "/home/touchtsu/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_detect/nodes/detect_sign", line 257, in <module>
    node = DetectSign()
  File "/home/touchtsu/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_detect/nodes/detect_sign", line 34, in __init__
    self.fnPreproc()
  File "/home/touchtsu/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_detect/nodes/detect_sign", line 73, in fnPreproc
    self.kp2, self.des2 = self.sift.detectAndCompute(self.img2,None)
cv2.error: /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/opencv_contrib/xfeatures2d/src/sift.cpp:1121: error: (-5) image is empty or has incorrect depth (!=CV_8U) in function detectAndCompute

[detect_sign-1] process has died [pid 24061, exit code 1, cmd /home/touchtsu/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_detect/nodes/detect_sign /detect/image_input:=/camera/image_compensated /detect/image_input/compressed:=/camera/image_compensated/compressed /detect/image_output:=/detect/image_traffic_sign /detect/image_output/compressed:=/detect/image_traffic_sign/compressed __name:=detect_sign __log:=/home/touchtsu/.ros/log/6370a9da-7e85-11e8-90ab-40490f7faef9/detect_sign-1.log].
log file: /home/touchtsu/.ros/log/6370a9da-7e85-11e8-90ab-40490f7faef9/detect_sign-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done"

​it's not show "/detect/image_traffic_sign/compressed" on topic of rqt
If you know about this issue please give me answer.
Thank you

**Comment by kijongGil** [comment]
Hi @touchtsu :)
Could you give me more information?
What are all the commands you typed before the error occurred? and what did you use turtlebot3 model? real or gazebo?

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
