### ISSUE TITLE
[camera/image_proc-2] process has died 

### ISSUE THREAD

**Issue by DGCHAO** [ROBOTIS-GIT/turtlebot3_autorace#25]
I have a error message when I execute roslaunch turtlebot3_autorace_instinsic_camera_calibration.launch
process[republish-1]: started with pid [3405]
process[camera/image_proc-2]: started with pid [3406]
/opt/ros/kinetic/lib/image_proc/image_proc: error while loading shared libraries: libopencv_calib3d3.so.3.2: cannot open shared object file: No such file or directory
[camera/image_proc-2] process has died [pid 3406, exit code 127, cmd /opt/ros/kinetic/lib/image_proc/image_proc _approximate_sync:=true image_raw:=image __name:=image_proc __log:=/home/burger/.ros/log/ccdd3c4e-9ba4-11e8-9c4b-000c29da7948/camera-image_proc-2.log].
log file: /home/burger/.ros/log/ccdd3c4e-9ba4-11e8-9c4b-000c29da7948/camera-image_proc-2*.log
I think is libopencv_calib3d3.so.3.2 course this error,but I can't solve it.

How do I solve this?

**Comment by kijongGil** [comment]
Hi @DGCHAO :)
What is your ROS version?? and have you used opencv before?

**Comment by DGCHAO** [comment]
Thank you reply me.My ROS version is kinetic.This is my first time using OpenCV.I want reinstall of opencv3.If I look into /opt/ros/kinetic/lib, i see libopencv_calib3d.so, libopencv_calib3d.so.3.3, and libopencv_calib3d.so.3.3.1, but not what I need libopencv_calib3d.so.3.2 .

**Comment by DGCHAO** [comment]
Hi @kijongGil 
Unfortunately, I still have not solved this problem.  I have tried several methods, update ubuntu, create a 3.2 to 3.3 soft connection, and modify ld.so.conf.I can't find a way.

**Comment by kijongGil** [comment]
I'm sorry for late reply.
It is hard to answer about opencv. I recommend formatting ubuntu and installing ROS according to the following manuals.
http://emanual.robotis.com/docs/en/platform/turtlebot3/pc_setup/#install-ubuntu-on-remote-pc

**Comment by DGCHAO** [comment]
Thank you

**Comment by DGCHAO** [comment]
I have solved the problem.I create a symlink from libopencv_calib3d3.so.3.3 to libopencv_calib3d3.so.3.2.It is work now.
