### ISSUE TITLE
No module named turtlebot3_autorace_camera.cfg

### ISSUE THREAD

**Issue by GToidZ** [ROBOTIS-GIT/turtlebot3_autorace#26]
After I did the both camera calibration and intrinsic calibration, I went ahead to extrinsic calibration. I got an error after ```roslaunch turtlebot3_autorace_camera turtlebot3_autorace_extrinsic_camera_calibration.launch``` From what I read on the console it is a Python error showing the **turtlebot3_autorace_camera.cfg** cannot be imported.

**Comment by kijongGil** [comment]
Hi, @GToidZ :)
I'm sorry for late reply.
Could you try to follow command?

`sudo chmod +x turtlebot3_autorace_camera.cfg`

Thanks,
Gilbert.

**Comment by GToidZ** [comment]
@kijongGil Thanks for the reply, but I have already fixed it by reinstalling the ROSCore; and I apologized that I forgot to close the issue.

**Comment by kijongGil** [comment]
That's ok @GToidZ. If you have any other questions, feel free to ask. Thanks.
