### ISSUE TITLE
Unable to Parking

### ISSUE THREAD

**Issue by Ayensyarah** [ROBOTIS-GIT/turtlebot3_autorace#31]
unable to parking even the parking sign already detected.

can you help me?

**Comment by RyanJaehyunShim** [comment]
@Ayensyarah 

Can you give us more details about your questions (i.e., which tutorial or error code)

Regards,
Ryan

**Comment by Ayensyarah** [comment]
@RyanJaehyunShim 

theres no error when i roslaunch autorace_core and sent data rostopic pub -1 /core/decided_mode std_msgs/UInt8 "data: 2". its follow the line.

then it detect parking sign but not change to parking mode. still following the line

**Comment by RyanJaehyunShim** [comment]
@Ayensyarah 

There is a misunderstanding about the mechanism. Once the robot detects a parking sign, it will start to count the number of dots on the line. When the robot finds the dotted line you can see on the racing map (by counting the number of dots), it will move to the parking lot.

Regards,
Ryan

**Comment by Ayensyarah** [comment]
@RyanJaehyunShim 

the i should change the dotted value in which file?
detect_parking.py right?

**Comment by RyanJaehyunShim** [comment]
@Ayensyarah 

You need the map.

**Comment by Ayensyarah** [comment]
@RyanJaehyunShim 

how can i get the mapping? i mean how can i mapping the map.

**Comment by RyanJaehyunShim** [comment]
@Ayensyarah 

Refer to 13.6.1 and 13.6.2 if you want to test it on a simulator. If you need a physical map, refer to the following link (https://github.com/ROBOTIS-GIT/autorace_track).

**Comment by arixrobotics** [comment]
Is this where it counts and check the dotted line? https://github.com/ROBOTIS-GIT/turtlebot3_autorace/blob/master/turtlebot3_autorace_detect/nodes/detect_parking#L220 

If yes, then it triggers even if it sees only 1 dot? Or it counts until a few dots, then start to go in?

**Comment by RyanJaehyunShim** [comment]
@arixrobotics 

Yes, the latter is correct. You can modify the code and try it again, then you will know it.

Regards,
Ryan

**Comment by ROBOTIS-Kayman** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
