### ISSUE TITLE
AWS Rekognition error "VideoDetect instance has no attribute 'GetResultsFaces'"

### ISSUE THREAD

**Issue by tiwaris436** [ROBOTIS-GIT/turtlebot3_autorace#35]
I am getting this error while running codes for Detect faces in awscli.

"self.GetResultsFaces(rekMessage['JobId'])
AttributeError: VideoDetect instance has no attribute 'GetResultsFaces'"

Here is the link of Doc which I am referring.
https://docs.aws.amazon.com/rekognition/latest/dg/API_StartFaceDetection.html

**Comment by RyanJaehyunShim** [comment]
@tiwaris436 

Please contact Amazon and ask your question

Regards,
Ryan
