### ISSUE TITLE
Unable to Save  Intrinsic Camera Calibration 13.2.4.2

### ISSUE THREAD

**Issue by red24dog** [ROBOTIS-GIT/turtlebot3_autorace#44]
Display window shows Checkerboard, data was "added" but Save Button appears inactive.
In spite Intrinsic (4.2) and Extrinsic (4.3) calibration functions display the checkerboard and outline the lanes iwith a red box seemed to work.

13.2.4.2. Tutorials:4.2 Intrinsic Camera Calibration
Step 4. (herschel is Remote PC)
turtlebot@herschel:~$ roslaunch turtlebot3_autorace_camera turtlebot3_autorace_intrinsic_camera_calibration.launch
... logging to /home/turtlebot/.ros/log/a6dc4fb4-c856-11e9-932b-60d819ca036d/roslaunch-herschel-5907.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://herschel.local:33241/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    cameracalibrator (camera_calibration/cameracalibrator.py)
    republish (image_transport/republish)

ROS_MASTER_URI=http://herschel.local:11311

process[republish-1]: started with pid [5924]
process[cameracalibrator-2]: started with pid [5925]
('Waiting for service', '/camera/set_camera_info', '...')
OK
*** Added sample 1, p_x = 0.547, p_y = 0.629, p_size = 0.366, skew = 0.117
^C[cameracalibrator-2] killing on exit
[republish-1] killing on exit
QObject::~QObject: Timers cannot be stopped from another thread
shutting down processing monitor...
... shutting down processing monitor complete
done
turtlebot@herschel:~$ 

***Unable to Save***

Had to ctrl-c

turtlebot@herschel:~/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_camera/calibration/intrinsic_calibration$ cat camerav2_320x240_30fps.yaml
image_width: 320
image_height: 240
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [164.595714370777, 0, 155.7296974048595, 0, 165.5485348916819, 108.2763701447475, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.2909375306628219, 0.05890305811963341, 0.002023707366213156, 0.002460957243230047, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [113.093635559082, 0, 156.4088907842834, 0, 0, 131.5423431396484, 102.2805583769696, 0, 0, 0, 1, 0]
turtlebot@herschel:

**Comment by rjshim** [comment]
@red24dog 

Sorry for the late reply. When you are done with calibration, you will be able to click the save and upload buttons. Once you click the upload button, a yaml file (or tat file including a yaml file) with calibration info will be created. Overwrite the file of the path below with that yaml file.

> turtlebot3_autorace_camera/calibration/intrinsic_calibration/Camera2_320x24030fps.yaml.  

If you would like to know more details about the process, please refer to the [link](http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration)

Let us know if you have more questions, 
Ryan

**Comment by rjshim** [comment]
As there have been no updates, I am closing this issue.
