### ISSUE TITLE
13.2.5. Tutorials Missions, 5.1 Lane Detection Errors

### ISSUE THREAD

**Issue by red24dog** [ROBOTIS-GIT/turtlebot3_autorace#45]
Tutorials 4.4 Recognition Worked, with the following status
turtlebot@herschel:~$ rosnode list
/camera
/camera/image_compensation
/camera/image_compensation_projection
/camera/image_proc
/camera/image_projection
/detect_lane
/republish
/rosout

13.2.5 Tutorials: 5. Missions
13.2.5.1
Tutorials: 5.1 Lane Detection
Step 2 Had errors and unable to display /detect/image_yellow, /detect/image_white, /image_lane/compressed. 

Step 6 Remote PC control_lane.launch worked but SBR robot.launch did nut move turtlebot.

Here is log of Steps 2, 3, 4, 5 ,6 with rosnode list and info /detect_lane displayed at end. I would appreciate your assessment and suggested troubleshooting.

Step 2 (herschel is Remote PC, cassini is SBC))
Remote PC 
turtlebot@herschel:~$ export AUTO_DT_CALIB=calibration
turtlebot@herschel:~$ roslaunch turtlebot3_autorace_detect turtlebot3_autorace_detect_lane.launch
... logging to /home/turtlebot/.ros/log/198c87ea-c861-11e9-932b-60d819ca036d/roslaunch-herschel-9171.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://herschel.local:40551/

SUMMARY
========

PARAMETERS
 * /detect_lane/detect/lane/white/hue_h: 25
 * /detect_lane/detect/lane/white/hue_l: 0
 * /detect_lane/detect/lane/white/lightness_h: 255
 * /detect_lane/detect/lane/white/lightness_l: 180
 * /detect_lane/detect/lane/white/saturation_h: 36
 * /detect_lane/detect/lane/white/saturation_l: 0
 * /detect_lane/detect/lane/yellow/hue_h: 41
 * /detect_lane/detect/lane/yellow/hue_l: 27
 * /detect_lane/detect/lane/yellow/lightness_h: 255
 * /detect_lane/detect/lane/yellow/lightness_l: 160
 * /detect_lane/detect/lane/yellow/saturation_h: 255
 * /detect_lane/detect/lane/yellow/saturation_l: 130
 * /detect_lane/is_detection_calibration_mode: True
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    detect_lane (turtlebot3_autorace_detect/detect_lane)

ROS_MASTER_URI=http://herschel.local:11311

process[detect_lane-1]: started with pid [9188]
[INFO] [1566865776.199803]: [Detect Lane] Detect Lane Calibration Parameter reconfigured to
[INFO] [1566865776.205698]: hue_white_l : 0
[INFO] [1566865776.207552]: hue_white_h : 179
[INFO] [1566865776.212005]: saturation_white_l : 0
[INFO] [1566865776.214347]: saturation_white_h : 255
[INFO] [1566865776.218111]: lightness_white_l : 0
[INFO] [1566865776.224628]: lightness_white_h : 255
[INFO] [1566865776.226270]: hue_yellow_l : 0
[INFO] [1566865776.227346]: hue_yellow_h : 179
[INFO] [1566865776.231429]: saturation_yellow_l : 0
[INFO] [1566865776.234830]: saturation_yellow_h : 255
[INFO] [1566865776.237661]: lightness_yellow_l : 0
[INFO] [1566865776.241728]: lightness_yellow_h : 255

(See Step 3 rqt below).

After running rqt
shutdown request: new node registered with same name
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
[detect_lane-1] process has finished cleanly
log file: /home/turtlebot/.ros/log/198c87ea-c861-11e9-932b-60d819ca036d/detect_lane-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
turtlebot@herschel:~$ 

Step 3 rqt
Remote PC
turtlebot@herschel:~$ rqt
[ERROR] [1566865915.071796774]: Tried to advertise a service that is already advertised in this node [/rqt_gui_cpp_node_9269/compressed/set_parameters]
[ERROR] [1566865915.302174883]: Tried to advertise a service that is already advertised in this node [/rqt_gui_cpp_node_9269/compressed/set_parameters]
[ WARN] [1566865958.476261966]: [image_transport] It looks like you are trying to subscribe directly to a transport-specific image topic '/camera/image_extrinsic_calib/compressed', in which case you will likely get a connection error. Try subscribing to the base topic '/camera/image_extrinsic_calib' instead with parameter ~image_transport set to 'compressed' (on the command line, _image_transport:=compressed). See http://ros.org/wiki/image_transport for details.
[ERROR] [1566865994.449852480]: Tried to advertise a service that is already advertised in this node [/rqt_gui_cpp_node_9269/compressed/set_parameters]
[ERROR] [1566866096.398407099]: Tried to advertise a service that is already advertised in this node [/rqt_gui_cpp_node_9269/compressed/set_parameters]
[ERROR] [1566866117.419340389]: Tried to advertise a service that is already advertised in this node [/rqt_gui_cpp_node_9269/compressed/set_parameters]
[ERROR] [1566866121.707539976]: Tried to advertise a service that is already advertised in this node [/rqt_gui_cpp_node_9269/compressed/set_parameters]
[ERROR] [1566866123.991775450]: Tried to advertise a service that is already advertised in this node [/rqt_gui_cpp_node_9269/compressed/set_parameters]

Step 4. No displays
Step 5.
Remote PC
turtlebot@herschel:~$ export AUTO_DT_CALIB=action
turtlebot@herschel:~$ roslaunch turtlebot3_autorace_detect turtlebot3_autorace_detect_lane.launch
... logging to /home/turtlebot/.ros/log/198c87ea-c861-11e9-932b-60d819ca036d/roslaunch-herschel-9491.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://herschel.local:39667/

SUMMARY
========

PARAMETERS
 * /detect_lane/detect/lane/white/hue_h: 25
 * /detect_lane/detect/lane/white/hue_l: 0
 * /detect_lane/detect/lane/white/lightness_h: 255
 * /detect_lane/detect/lane/white/lightness_l: 180
 * /detect_lane/detect/lane/white/saturation_h: 36
 * /detect_lane/detect/lane/white/saturation_l: 0
 * /detect_lane/detect/lane/yellow/hue_h: 41
 * /detect_lane/detect/lane/yellow/hue_l: 27
 * /detect_lane/detect/lane/yellow/lightness_h: 255
 * /detect_lane/detect/lane/yellow/lightness_l: 160
 * /detect_lane/detect/lane/yellow/saturation_h: 255
 * /detect_lane/detect/lane/yellow/saturation_l: 130
 * /detect_lane/is_detection_calibration_mode: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    detect_lane (turtlebot3_autorace_detect/detect_lane)

ROS_MASTER_URI=http://herschel.local:11311

process[detect_lane-1]: started with pid [9508]
[ERROR] [1566866401.293735]: bad callback: <bound method DetectLane.cbFindLane of <__main__.DetectLane instance at 0x7f70287c5170>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/turtlebot/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_detect/nodes/detect_lane", line 169, in cbFindLane
    self.left_fit = np.array([np.mean(self.mov_avg_left[::-1][:, 0][0:MOV_AVG_LENGTH]),
AttributeError: DetectLane instance has no attribute 'mov_avg_left'

[ERROR] [1566866422.765454]: bad callback: <bound method DetectLane.cbFindLane of <__main__.DetectLane instance at 0x7f70287c5170>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/turtlebot/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_detect/nodes/detect_lane", line 169, in cbFindLane
    self.left_fit = np.array([np.mean(self.mov_avg_left[::-1][:, 0][0:MOV_AVG_LENGTH]),
AttributeError: DetectLane instance has no attribute 'mov_avg_left'

Proceeded with Step 6 anyway - No errors.

Remote PC
turtlebot@herschel:~$ roslaunch turtlebot3_autorace_control turtlebot3_autorace_control_lane.launch
... logging to /home/turtlebot/.ros/log/198c87ea-c861-11e9-932b-60d819ca036d/roslaunch-herschel-9647.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://herschel.local:36991/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    control_lane (turtlebot3_autorace_control/control_lane)

ROS_MASTER_URI=http://herschel.local:11311

process[control_lane-1]: started with pid [9665]

SBC
turtlebot@cassini:~$ roslaunch turtlebot3_bringup turtlebot3_robot.launch
... logging to /home/turtlebot/.ros/log/198c87ea-c861-11e9-932b-60d819ca036d/roslaunch-cassini-1881.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cassini.local:35157/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://herschel.local:11311

process[turtlebot3_core-1]: started with pid [1890]
process[turtlebot3_lds-2]: started with pid [1891]
process[turtlebot3_diagnostics-3]: started with pid [1892]
[INFO] [1566866721.008644]: ROS Serial Python Node
[INFO] [1566866725.489002]: Connecting to /dev/ttyACM0 at 115200 baud
[INFO] [1566866729.541343]: Note: publish buffer size is 1024 bytes
[INFO] [1566866729.544723]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1566866730.209101]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1566866730.448634]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1566866730.878875]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1566866732.768535]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1566866733.009515]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1566866733.209090]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1566866733.553209]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1566866741.590189]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1566866742.701737]: Note: subscribe buffer size is 1024 bytes
[INFO] [1566866742.708760]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
[INFO] [1566866742.773208]: Setup subscriber on sound [turtlebot3_msgs/Sound]
[INFO] [1566866742.826926]: Setup subscriber on motor_power [std_msgs/Bool]
[INFO] [1566866742.907338]: Setup subscriber on reset [std_msgs/Empty]
[WARN] [1566866743.076391]: Failed to get param: timeout expired
[INFO] [1566866743.081353]: Setup TF on Odometry [odom]
[INFO] [1566866743.086188]: Setup TF on IMU [imu_link]
[INFO] [1566866743.090881]: Setup TF on MagneticField [mag_link]
[INFO] [1566866743.095719]: Setup TF on JointState [base_link]
[INFO] [1566866743.105887]: --------------------------
[INFO] [1566866743.111085]: Connected to OpenCR board!
[INFO] [1566866743.116548]: This core(v1.2.2) is compatible with TB3 Burger
[INFO] [1566866743.121751]: --------------------------
[INFO] [1566866743.126688]: Start Calibration of Gyro
[INFO] [1566866743.131928]: Calibration End
[ERROR] [1566866758.137776]: Lost sync with device, restarting...
[INFO] [1566866758.147911]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1566866758.153338]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1566866758.159407]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1566866758.164928]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1566866758.170356]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1566866758.176126]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1566866758.181540]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1566866758.186941]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1566866758.192366]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1566866761.571954]: Setup TF on Odometry [odom]
[INFO] [1566866761.577633]: Setup TF on IMU [imu_link]
[INFO] [1566866761.582497]: Setup TF on MagneticField [mag_link]
[INFO] [1566866761.587444]: Setup TF on JointState [base_link]
[INFO] [1566866761.613977]: --------------------------
[INFO] [1566866761.619451]: Connected to OpenCR board!
[INFO] [1566866761.625284]: This core(v1.2.2) is compatible with TB3 Burger
[INFO] [1566866761.631400]: --------------------------
[INFO] [1566866761.637197]: Start Calibration of Gyro
[INFO] [1566866764.135023]: Calibration End

*** No motion ***

Running ~:rqt_image_view shows /camera/image/compresses but no /detect/image_lane/compressed
running rosnode info /detect_lane shows /detect/image_lane/compressed [sensor_msgs/CompressedImage] is being published.

turtlebot@herschel:~$ rosnode list
/camera
/camera/image_compensation
/camera/image_compensation_projection
/camera/image_proc
/camera/image_projection
/control_lane
/detect_lane
/republish
/rosout
/turtlebot3_core
/turtlebot3_diagnostics
/turtlebot3_lds
turtlebot@herschel:~$ 
turtlebot@herschel:~$ rosnode info /detect_lane
--------------------------------------------------------------------------------
Node [/detect_lane]
Publications: 
 * /detect/image_lane/compressed [sensor_msgs/CompressedImage]
 * /detect/lane [std_msgs/Float64]
 * /detect/white_line_reliability [std_msgs/UInt8]
 * /detect/yellow_line_reliability [std_msgs/UInt8]
 * /rosout [rosgraph_msgs/Log]

Subscriptions: 
 * /camera/image_projected_compensated [sensor_msgs/Image]

Services: 
 * /detect_lane/get_loggers
 * /detect_lane/set_logger_level

contacting node http://herschel.local:39457/ ...
Pid: 9508
Connections:
 * topic: /detect/lane
    * to: /control_lane
    * direction: outbound
    * transport: TCPROS
 * topic: /rosout
    * to: /rosout
    * direction: outbound
    * transport: TCPROS
 * topic: /camera/image_projected_compensated
    * to: /camera/image_compensation_projection (http://herschel.local:40143/)
    * direction: inbound
    * transport: TCPROS

turtlebot@herschel:~$ 

_

**Comment by rjshim** [comment]
@Robolover

**Comment by Robolover** [comment]
@red24dog 
Hi.
Try again in e-manual from Tutorials: 5.1 Lane Detection.
If you still get the same error, reply to me 
Thank you.

**Comment by rjshim** [comment]
As there have been no updates, I am closing this issue.
