### ISSUE TITLE
after git clone the repository from Turtlebot3, when i cd catkinws and cmake, screen hang

### ISSUE THREAD

**Issue by timlo94** [ROBOTIS-GIT/turtlebot3_autorace#5]
first i go cd catkinws/src and i git clone this repository, afterward i cmake and the screen hang directly at 93%. i had perform apt update,upgrade,remove . Even after i reboot the raspberrypi3, i can still run the node with some error. like lane_detection no PYTHON EXTENSION. should be lane_detection.py!!!!

**Comment by ROBOTIS-Leon** [comment]
@timlo94 

Sorry,
first of all, I should change all the python files' name to nonextension.
I will update after the modification.

**Comment by ROBOTIS-Leon** [comment]
@timlo94 

It must be fixed now. 
Let's go ahead

**Comment by timlo94** [comment]
thanks for your hard work. i will try it tomorrow morning.

**Comment by robotpilot** [comment]
Thanks, please let us know if you have any other problems.

**Comment by timlo94** [comment]
After redownload and compile, it was successful. But after run the intrinsic camera calibration, the displau rqt gui dimmed and show nothing, and the lainch node cannot be runned due to CVbridge error

**Comment by robotpilot** [comment]
@ROBOTIS-Leon , 
We need your guidance about camera calibration and dependency package.

**Comment by robotpilot** [comment]
@kijongGil 
Has this problem been resolved? 
Please take a look at this issue and add a detailed description of it to e-manual.
http://emanual.robotis.com/docs/en/platform/turtlebot3/autonomous_driving/#autonomous-driving

**Comment by timlo94** [comment]
Not yet solved. It seems like module object has no attribute, CVbridge error simply cannot solve just by downloaded respective dependencies or update/install relevant packages. By the way i am using raspicam, i am not sure whether your cv using usbcam or not.


And also ya, can i know is it other peoples who downloaded this repository also faced same situation? Or developer has tested the code several times before release?.



Thanks a lot for developer senior research engineer on this matter. Your problem solving skills is appreciated .

**Comment by ROBOTIS-Leon** [comment]
@timlo94

Hi and sorry for the late reply.
I couldn’t notice that there was some extra questions, since I was in the vacation.

the attached shows something weird; if you ran the catkin make, the opencv bridge must be installed by the joined dependent package. so anyway the error means the cv bridge couldnt be found via python in your computer. 
try sudo apt-get install ros-kinetic-cv-bridge.

readme.md shows how and what kinda camera should be used for this code. See the description carefully.

There are number of users who ran the code already in their robots. I personally think that you are able to handle

**Comment by timlo94** [comment]
![20180529_145719](https://user-images.githubusercontent.com/32585422/40642810-b14ef636-630d-11e8-97a7-b458f37fa0e8.jpg)
![Uploading 20180529_145437.jpg…]()

**Comment by timlo94** [comment]
![20180529_145719](https://user-images.githubusercontent.com/32585422/40642847-c5b01254-630d-11e8-8ace-22aab7fbdf48.jpg)
![20180529_145437](https://user-images.githubusercontent.com/32585422/40642848-c5e803a8-630d-11e8-939f-3e17bdc64dbb.jpg)

**Comment by timlo94** [comment]
My cv bridge is up to date and i had follow readme,just my camera used is normal raspberry pi camera( from official turtlebot)

**Comment by timlo94** [comment]
Thanks for updating the repository.

**Comment by kijongGil** [comment]
Hi, @timlo94
How are you doing?

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
